name: OSMatrix

on:
  workflow_dispatch:

jobs:
  message:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Say hello to the OS
        run: echo "Hello from ${{ matrix.os }}"
